on:
 push:
jobs:
  example_matrix:
    strategy:
      matrix:
       color: [green, pink]
       animal: [owl, magpie]
       include:
        - color: blue
          animal: owl
        - color: pink
          animal: magpie
    runs-on: windows-latest
    steps:
    - run: echo ${{ matrix.animal }}  ${{ matrix.color }}  
   
